name: Run tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/readon/spinalhdl-docker:master
    steps:
    - uses: actions/checkout@v3
    - run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Get submodules
      shell: bash
      run: git submodule update --init --recursive
    - run: sbt Test/compile
    - uses: actions/cache/save@v3
      with:
        path: |
          **/target
        key: ${{ runner.os }}-compiled-${{ github.sha }}

  idslplugin-test:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/readon/spinalhdl-docker:master
    steps:
    - uses: actions/checkout@v3
    - run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - uses: ./.github/actions/get-compiled
    - run: sbt idslplugin/test

  idslpayload-test:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/readon/spinalhdl-docker:master
    steps:
    - uses: actions/checkout@v3
    - run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - uses: ./.github/actions/get-compiled
    - run: sbt idslpayload/test

  core-test:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/readon/spinalhdl-docker:master
    steps:
    - uses: actions/checkout@v3
    - run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - uses: ./.github/actions/get-compiled
    - run: sbt 'core/testOnly * -- -l spinal.tester.formal'

  core-formal:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/readon/spinalhdl-docker:master
    steps:
    - uses: actions/checkout@v3
    - run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - uses: ./.github/actions/get-compiled
    - run: sbt 'core/testOnly * -- -n spinal.tester.formal'

  sim-test:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/readon/spinalhdl-docker:master
    steps:
    - uses: actions/checkout@v3
    - run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - uses: ./.github/actions/get-compiled
    - run: sbt sim/test

  tester-test:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/readon/spinalhdl-docker:master
    steps:
    - uses: actions/checkout@v3
    - run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - uses: ./.github/actions/get-compiled
    - run: sbt 'tester/testOnly * -- -l spinal.tester.formal'

  tester-formal:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/readon/spinalhdl-docker:master
    steps:
    - uses: actions/checkout@v3
    - run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - uses: ./.github/actions/get-compiled
    - run: sbt 'tester/testOnly * -- -n spinal.tester.formal'

  lib-test:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/readon/spinalhdl-docker:master
    steps:
    - uses: actions/checkout@v3
    - run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - uses: ./.github/actions/get-compiled
    - run: sbt 'lib/testOnly * -- -l spinal.tester.formal'

  lib-formal:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/readon/spinalhdl-docker:master
    steps:
    - uses: actions/checkout@v3
    - run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - uses: ./.github/actions/get-compiled
    - run: sbt 'lib/testOnly * -- -n spinal.tester.formal'

  scaladoc:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/readon/spinalhdl-docker:master
    steps:
    - uses: actions/checkout@v3
    - run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - uses: ./.github/actions/get-compiled
    - run: sbt unidoc
